base_url = "https://sstork.dev"
theme = "linkita"

title = "sstork.dev"
author = "Sebastian Stork"
generate_feeds = true
taxonomies = [
  { name = "tags", feed = true, paginate_by = 10 },
]

[markdown]
highlight_code = true
highlight_theme = "material-dark"
render_emoji = true
bottom_footnotes = true

[extra]
header_menu_name = "menu_name"

[extra.menus]
menu_name = [
  { url = "$BASE_URL/tags/", name = "Tags" },
  { url = "$BASE_URL/about/", name = "About" },
]

[extra.profiles."Sebastian Stork"]
avatar_url = "images/stork-avatar.jpg"
name = "Sebastian Stork"
bio = "CS Student & Nix enthusiast"
social = [
  { name = "github", url = "https://github.com/SebastianStork" },
  { name = "forgejo", url = "https://git.sstork.dev/SebastianStork" },
  { name = "linkedin", url = "https://www.linkedin.com/in/sebastian-stork" },
  { name = "rss", url = "$BASE_URL/atom.xml" },
]
