base_url = "https://sstork.dev"
theme = "kita"

title = "sstork.dev"
author = "Sebastian Stork"
generate_feeds = true
taxonomies = [
  { name = "tags", feed = true, paginate_by = 10 },
]

[markdown]
highlight_code = true

[[extra.menu]]
name = "Tags"
url = "$BASE_URL/tags/" 

[[extra.menu]]
name = "About"
url = "$BASE_URL/about/"

[extra.profile]
avatar_url = "images/stork.svg"
name = "Sebastian Stork"
bio = "CS Student & Nix enthusiast"

[[extra.profile.social]]
name = "github"
url = "https://github.com/SebastianStork"

[[extra.profile.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/sebastian-stork"

[[extra.profile.social]]
name = "email"
url = "mailto:sebastian.stork@pm.me"

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/atom.xml"
